name: First workflow
on: push

jobs:
  echo-hello:
      runs-on: ubuntu-latest
      steps:
          - name: hello world
            run: echo 'hello worl'
  echo-goodbye:
      runs-on: ubuntu-latest
      steps:
          - name: goodbye world
            run: |
              echo 'i will fail'
              exit 1
            